apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-statefulsets
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "patch", "list", "watch"]

