apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-of-terms-comunica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-of-terms-comunica
  template:
    metadata:
      labels:
        app: network-of-terms-comunica
    spec:
      containers:
        - name: network-of-terms-comunica
          image: docker.pkg.github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/network-of-terms-comunica
          ports:
            - containerPort: 3123
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: network-of-terms-comunica
spec:
  ports:
    - port: 80
      targetPort: 3123
  selector:
    app: network-of-terms-comunica
