apiVersion: v1
kind: Secret
metadata:
    name: backup-s3
    namespace: nde
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:5/DPye0AcuS2GEJiLKyiC7FNFj67DyvaD9Jr2S/U/Q+9Fto=,iv:49EmWbL/hWatoKYu7wR96rF+Di/qP5ysQm/z06ClVZU=,tag:+9484pJ2K5GysSTZSBr0vQ==,type:str]
    bucket: ENC[AES256_GCM,data:EHy35HeZ1vTBrFie,iv:abg9Sjh9ONC1cgtnrVXYHiVpinlEcHzw62QiJPf8AWU=,tag:ynehargcT1MGc9oxcrN4QA==,type:str]
    access-key: ENC[AES256_GCM,data:ihkqX/Nf0gOjODVm1+Hhc1Vp45w=,iv:GnyWXZDeule8EMeERyKw0lDv4TBE0Oln57lWKbODvB0=,tag:bVZi9fjjFiWkS4GtVWOADQ==,type:str]
    secret-key: ENC[AES256_GCM,data:FEsVtbCKbT8oDsb5cLfIMJKP0KMLRzh+55PJha2aKQCyWSKllGECcVOEYg==,iv:v0/dH0j3LhrnOPSrz2O6aryVqjJ0mJGqFmtISJSnnNM=,tag:FcnLi9dFK2N9+VVVLXGf0A==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYWtxd2Yya212aTAwZXhE
            WGVmK29sdElIbEFORzlOM2pCWHBkN1hRbkdRCnJ0RVovVURGM1EvNk9sMWZCRjJt
            dmN4WXBmaXN2cnZscTZ5ZXNKZ0cxbnMKLS0tIEwyQmd1WU5wc3g4ZFJKckpFMVVv
            WjZtbHJTYTE0em0wNDcvQ1JkZHlvZWcKJry24L2eT+1ZPZd0hPwXFzpC+iC78r9J
            8NB5MnQEizyyzPN3lIL9KIleU3nYg69si5f6vmB/3AZRyJ4Vw6+y1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T12:53:23Z"
    mac: ENC[AES256_GCM,data:MspQihw/f4ASzguT9SX3aw3MkOlXxL8n1Fpe7iirskZr/vJ8GFWnAccmgvAV+sjHtY7eSlLcxkbbd3VsTBEpFKkkcgx74ddQ5wG9MK6zTzFx7llZumJfV88Ksi0kCo4eDVcnRrWx58oV1ODrOiywMagHCj61RrOz5IzazTyX3bA=,iv:o3GjSqlX9glCDJq5GMCbxbNRet2TQxTJ6wFzKocW+Tk=,tag:wPa9MF3iZ7G1JuLW92nlTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
