apiVersion: v1
data:
    password: ENC[AES256_GCM,data:/OzUflr/ao1cu3iJ5LdVGxvUrWfI0mn8utcwItS5/ErFoVCZcjnto83sRbFkduWN,iv:yr63vuJk3aOSnfhZMO6YwHaG4zrgj+uKLbnk6vck6fc=,tag:EXu93FJdpMHU5U3zXCLoSw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mattermost-smtp
    namespace: nde
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb0JzUFFITUczKzVHSUpF
            TWhJbHQ2bktzWG5rNkgyV1AwcVRzL2JFS1dFCnJ3WVlwOTg2L0FDdlZJR3ZFTG5Y
            ZnlKOUp3cU5EZzNzVm5BSVh5SDR3d2MKLS0tIDBNL2czVWtyVjNTanB0T2xEWFFF
            UXhyOStGM1ZNOXJnOE9qUlNaN3YrZGsKdRDv83MdGxKWvIQ/Rlu9lIWDGfAvfM2F
            oL93jDyX7a/qlFW2XzLP3gjHjPQgbzJewPHGwDQKVOSRyGPxVJT95A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T14:07:18Z"
    mac: ENC[AES256_GCM,data:3oI/nF0RdvGxBNquFtwq5Vi9jiqNsJ4b0YYtSQoE3hq3lhVGHUFL/g1bcXjSOQsmWPzsUdGV2FHar0B3NXfVlXkbz69zqzSA4QuObjT8Cd9JVE1uuMVjFggYHr6+F4yxYWtQ0cEzBs4RufN6Ax3zQ28DMAFmrsIxu74sM2AQsSw=,iv:zYoKocxzYW5CmFeMHOIbExuJDOwo/SBjIC1vg41ccIQ=,tag:DkVGcj0kKeZEItH0r/pZsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
