apiVersion: v1
data:
    gtaaCredentials: ENC[AES256_GCM,data:P4vz0pxuDIMBkGFXFyOhqOKyBNsAZhNvRyjFKza+kofvOLRgqf+0t05CnUk=,iv:Tjf/HBwtw96BbK0qZTM0j6OUUNz+GAvtFgShbcWhLpg=,tag:/7pAJnUpulZ1h88NquYtAw==,type:str]
kind: Secret
metadata:
    name: network-of-terms
    namespace: nde
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1739xnpat5cfex8u6eq7ljujj274z2wdta740g4mnsjfnc4stzcdq4508z7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWlhxY3hhSUhsQ21PaWJ3
            R3JhYjVvdVB6WjdFeFhmL2NZWGNPMy9heldBCnc1YkY2bFgwODhyaUUzc29LMEc0
            ZUYzRlJOM3plUGJKcC9vOGh1ZTYvakkKLS0tIEN4cWtBeFRnRGtiTDVIRmFibmVY
            c1ZZQyswN3cxT0RoMHhQaG1TRGovbncK0Kr8YTeO6p2C56YyThE9v8pUEcDI4ZMh
            YxwJssmc41bmYlW9Xxq8eqrfr9VdE08F+uIOa3/m3qH3qSgMXuhZOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-10T09:49:48Z"
    mac: ENC[AES256_GCM,data:awZTWbikMULP+SRtd433pbZ0Rd6aKG+1yRYbjclPJmzeRYq1WNatkS2fmmXKj1mGR1K7bN/h+ycdEKp0qPdbgA8XMgB5oF8XV66fLxqcfZ0CrAlMgrgnicMQgHy0Hf6dbMQYZJoBoTbJ0axbcL02MsCFaBhAnAsExMMWyR0W2pk=,iv:ik4huhgDBSMbZa3lTxlgkGDLZXFz+gRnQTTN3tD7JeM=,tag:L15Wr/hK2E51gXCDFYz6Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
