apiVersion: v1
data:
    otlp-headers: ENC[AES256_GCM,data:xtZVEGIiOQhXZmEdL/cFDyEZg7F2DIsdgKxZo65ZtSd8K2Tj56uNOjRDIkkT5tEe8hOdtBLwYg0aYnAtRHUUDHbG2PsrYBFL+WzyHQv4levKejHb0o4ROXb+vq+qQAUU1BP96ypKZIaAIP7xblVyxEHKcHQ=,iv:j8R8DLpnmXXLmaEtMzU+F0uWTgqyWKFV7xFsJPCdXXU=,tag:fDZ2v65mxM6BfYFhMd/Cww==,type:str]
kind: Secret
metadata:
    name: opentelemetry-collector-token
    namespace: nde
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUUxLQWNXdVFhMFN6QUdU
            SU5jOVcvZXNDZEhaVHErbUkyYUJ3WUVNZmpBCkxxUXZycEd6bUkremk5d21SUHFu
            RTNud3NzRkgyQnR3MkRHTHhFQ3I0MlEKLS0tIDVtWlVxNjBhazZtNkNHTkF3NjRW
            Wjg3V1p2aUJBaWUzdzFacjdTdFBaQXcKQYZdedlDyORtL70Z/4eXv/KGaCDEH8Zm
            RcQws7pYyikQXx7+W5F6Pz06gHbHJTKQvwTZyejx7ZRtfTYoH3flBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T16:53:18Z"
    mac: ENC[AES256_GCM,data:BPS7cgA8EfI8YByGF9RZ6/4i0M5q0C7K2S6nmFRRoya4obeF09invK7VMwNHTSNcTP/yxguueckBJjC0qjYBOnZrC0ur1nLDLNPgp5JN0H6/rV7FINiObGfaq4Y151uCKy1W3nIEcHdb7mNZ3+nDkcOz/ZDDN/FQFLBHGacXnMw=,iv:/B5/0HrIONNUlA18oLXG2LY3Qgdwu6P8U8bly3cck8w=,tag:krtn2ga6oN2Bb94eMLRqag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
