apiVersion: v1
data:
    token: ENC[AES256_GCM,data:ITUdZEPwZ0Cm5mE+kPcuUdRzDUfFGAz6WMmjQftBKOcxXw8bCeDxrQ1640HakR2SMyHbjmCI1w4ZooUiOy6Jtime/fS/QR0k5elVi/Ne9VCiPc2NyVpmiw==,iv:PTX+9rUxRDYqadM4aKA6ovrZkWdYKbHctT/DInM1qNs=,tag:RbbqDwGYGSfgA5f6nTpJ7g==,type:str]
kind: Secret
metadata:
    name: opentelemetry-collector-token
    namespace: nde
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWUlQaWYxTU1sajNnRVlN
            SjVhQjhZWmhuaDVFZEdGVHpJWU9XNzNZcFEwCjN2VU5aWmp4eTVocWNZdzRzTVIr
            SThHZDVrcThCelpvUnB5bng0N2JvcjAKLS0tIEhTcUplZHZoQ2NLNVB0QUJrTUd4
            dGlOUTlVZXpTMVdRbmhwa1hVS3kyL1UKAm1beJpaqUAIe4+RE0/wVkNVZRegG+sr
            6Gwh+mAiC6K+A+oKKcRWZQVW20Ysn3Str6t0GGwZUJhoGlj2D5IDDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T08:59:03Z"
    mac: ENC[AES256_GCM,data:ivdZmoBMdn0wKfO6Ya3lY3C93jjLFxq5qUlXfPddBGHr0wnLOoBGA2peBAOznSxu1en0yjuHMucjqfSxTG4yrmUGiMo3q3XbnDrkrTJeasACCCBVqgxoHXFkaE/cOTLwZAn7KTZIcQbJUuxGr8Awgpz/oVwLAYhCntkpF/uq/2M=,iv:t97yB8xu4GNAreO61cFLV1yr/wrqdrRcBbadVBrinp8=,tag:DGI1qS3XKcX68p0SW4WHYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
