apiVersion: v1
data:
    key: ENC[AES256_GCM,data:HyAknv6Woxg3zQajw9JDoNaEqRMtJFVrkuCSYZcIZGLtqSkEiq8Hkxf4cwI=,iv:/KD4VnAJY+IF3Vt1W9MV6QLEKHk5g4oDPDTcjiM5sWk=,tag:jkeLkR3R6Sts9eeS0PI4PQ==,type:str]
    secret: ENC[AES256_GCM,data:xKqwDZugCDG5bwihQHugj/hFy45WsNjalUo88Mb3lPoOhs0QwK1wy83Gh2M=,iv:lRRiijg+KUoB1n2tD6//ljtV3mqQBrNw3GeEBLOu5Hs=,tag:L4GK6upG+Ur/q+rbLkxusg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: s3
    namespace: nde
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcUdGRzV6TzR6bkVFQUpI
            bndRbS9rdlFSRTZkbTNiekJFTGpLN0JSNGcwCllPOXNJcU0zWENVaE02N3U0OWtx
            b3hRUCtLMlVHMXZJcXd4amJ3Ym1pcU0KLS0tIEZ0SVgvNEQyNFc3S05sbnBjTDBh
            SnY4RFVwZE5pOUozZ1pGeWtYbkNkOEEKxzKt2IWsD9WFvj6bag2j6pZNSUrRtBsg
            5hyp+6lG9YXyyzJ7zZN/rhLV3Af+fRozXFfnzx15hZ6AMMdJUmS2ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T09:48:17Z"
    mac: ENC[AES256_GCM,data:AUgE43ffiTIl3vlb2O60kI7G4MOv2J2/UlyBo07POFUrj0dnfc4UG3dEG7QbixPUUpf+JYigDeOo7OtzgM0QNADT/hRMFKB6TUcz6LoI3YjS+CpWKw5FpN8iSJITSTIqpSHg+KhVxXe5yXa4QEnNSDnMj/Q62Yb6RPf8OjvUjtc=,iv:KNc+OV/EgXyxQZ22ivjcHwPfw8s12xqh8WxtN1iGT44=,tag:mLxctIc3sPR6ewj3u1EyGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
