apiVersion: v1
kind: Secret
metadata:
    name: uptimerobot
    namespace: nde
type: Opaque
stringData:
    read-only-api-key: ENC[AES256_GCM,data:Itf9a/DKrlv8W3wL3u8ZR9ll8RQ1C7nwhWm1w6/gzfUl9g==,iv:aH1s7K4mR3Qpdq2N1GCL76anl8yU3HrdCdc4WDGQJoM=,tag:l6qyeH2llIYs7AEgBoHMRw==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWStLUEx2aG5tLzhmTVZt
            bXBncjRQWlc5SGIybkY4NlREUHMxdVVCemgwCnZUcFdFREZBcC9UTXBLRmg2NDNu
            Y01pTFR2UUNKWFd0Y2pLUWpoeEIvd2cKLS0tIDY5M2NnMk00Y1oyRVVudi9MeStn
            UFJzeFRTaWtuelRuRXdnMWFmdUxDM2sKDnBOCVsxKCHCL8b4NGDoATT+P2NwMfbJ
            zeYvXdt8PlK0jBVl2mhI19HnSg+soxDb/ZFLMcxp34FcSjQ+PH62mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T12:51:55Z"
    mac: ENC[AES256_GCM,data:spo8rQ55tPobr820oH9xMzG7Q6ej7jrt3Ha5rqoOZa0nY9UTmm6ewnlYZ2iFLjbRjPHOcWwEO+EdIn6dogUCdLjoMm5knnisqGtyJ4aIP7wOVejKQGZGAniTCAOrIkawyX7N1SNi9qdzZeYpAUQebZqYIIcg9zFmjKHBHcIIzDU=,iv:5KLLyUJhPUEoahDBOg5pzlBrubwEaQORAKTFkcJCfZg=,tag:UZhFqcMAoiAlkB/WNo7K3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
