apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoriametrics-agent
spec:
  selectAllByDefault: true
  replicaCount: 1
  inlineScrapeConfig: |
    - job_name: "prometheus"
      static_configs:
      - targets: ["opentelemetry-collector-headless:9090"]
  remoteWrite:
    - url: "http://vmsingle-victoriametrics-single-persisted.default.svc:8429/api/v1/write"

