apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoriametrics-single-persisted
spec:
  retentionPeriod: "12"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 16Gi
  extraArgs:
    opentelemetry.usePrometheusNaming: "true"
