apiVersion: apps/v1
kind: Deployment
metadata:
  name: makemyflix-nuxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makemyflix-nuxt
  template:
    metadata:
      labels:
        app: makemyflix-nuxt
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/makemyflix-nuxt
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_APP_BACKEND_URL
              value: "https://makemyflix.netwerkdigitaalerfgoed.nl/strapi"
      imagePullSecrets:
        - name: ghcr
