apiVersion: apps/v1
kind: Deployment
metadata:
  name: makemyflix-strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makemyflix-strapi
  template:
    metadata:
      labels:
        app: makemyflix-strapi
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/makemyflix-strapi
          ports:
            - containerPort: 1337
          env:
            - name: URL
              value: 'https://makemyflix.netwerkdigitaalerfgoed.nl/strapi'
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi
                  key: keys
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi
                  key: api-token-salt
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi
                  key: admin-jwt-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi
                  key: jwt-secret
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi
                  key: transfer-token-salt
            - name: DATABASE_HOST
              value: makemyflix-postgres
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_NAME
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: makemyflix-postgres
                    key: password
            - name: S3_PUBLIC_URL
              value: "https://nde-makemyflix-strapi.ams3.digitaloceanspaces.com"
            - name: S3_BUCKET
              value: nde-makemyflix-strapi
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi-s3
                  key: key
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: makemyflix-strapi-s3
                  key: secret
      imagePullSecrets:
        - name: ghcr
