# See https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        # Enable after DNS has been changed:
        # - demo.netwerkdigitaalerfgoed.nl
        - termennetwerk.netwerkdigitaalerfgoed.nl
        - termennetwerk-api.netwerkdigitaalerfgoed.nl
        - ldwizard.netwerkdigitaalerfgoed.nl
      secretName: tls
  rules:
    - host: demo.netwerkdigitaalerfgoed.nl
      http:
        paths:
          - backend:
              serviceName: demo
              servicePort: 80
    - host: demo.netwerkdigitaalerfgoed.nl
      http:
        paths:
          - path: /stories
            backend:
              serviceName: stories
              servicePort: 80
    - host: demo.netwerkdigitaalerfgoed.nl
      http:
        paths:
          - path: /datasets
            backend:
              serviceName: datasets
              servicePort: 80
    - host: termennetwerk-api.netwerkdigitaalerfgoed.nl
      http:
        paths:
          - backend:
              serviceName: network-of-terms-api
              servicePort: 80
    - host: termennetwerk.netwerkdigitaalerfgoed.nl
      http:
        paths:
          - backend:
              serviceName: network-of-terms-demo
              servicePort: 80
    - host: ldwizard.netwerkdigitaalerfgoed.nl
      http:
        paths:
          - backend:
              serviceName: ldwizard-erfgoedwizard
              servicePort: 80
