# See https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-of-terms-api
  annotations:
    cert-manager.io/issuer: letsencrypt-nde
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx-nde
  tls:
    - hosts:
        - termennetwerk-api.nde-dev.ms4.surfsara.nl
      secretName: termennetwerk-api-tls
  rules:
    - host: termennetwerk-api.nde-dev.ms4.surfsara.nl
      http:
        paths:
          - path: /(reconcile|preview|extend)(?:/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: network-of-terms-reconciliation
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: network-of-terms-graphql
                port:
                  number: 80