apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-of-terms-reconciliation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-of-terms-reconciliation
  template:
    metadata:
      labels:
        app: network-of-terms-reconciliation
    spec:
      containers:
        - name: app
          image: 4.1.7 # {"$imagepolicy": "nde:network-of-terms-reconciliation-policy"}
          env:
            - name: GTAA_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: network-of-terms
                  key: gtaaCredentials
            - name: TRUST_PROXY
              value: 'true'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-collector:4318"
          ports:
            - containerPort: 3123
          readinessProbe:
            httpGet:
              path: /reconcile
              port: 3123
      imagePullSecrets:
        - name: ghcr
