apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omeka-s-faq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omeka-s-faq
  serviceName: omeka-s-faq
  template:
    metadata:
      labels:
        app: omeka-s-faq
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/omeka-s-faq
          env:
            - name: PMF_DB_HOST
              value: omeka-s-faq-mysql
            - name: PMF_DB_USER
              valueFrom:
                secretKeyRef:
                  name: omeka-s-faq-mysql
                  key: username
            - name: PMF_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: omeka-s-faq-mysql
                  key: password
            - name: PMF_DB_TYPE
              value: mariadb
            - name: PMF_DB_NAME
              value: omeka_s_faq
          ports:
            - containerPort: 80
          volumeMounts:
            - name: omeka-s-faq
              mountPath: /var/www/html/config
              subPath: config
            - name: omeka-s-faq
              mountPath: /var/www/html/attachments
              subPath: attachments
            - name: omeka-s-faq
              mountPath: /var/www/html/data
              subPath: data
            - name: omeka-s-faq
              mountPath: /var/www/html/images
              subPath: images
      imagePullSecrets:
        - name: ghcr
  volumeClaimTemplates:
    - metadata:
        name: omeka-s-faq
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: do-block-storage
