# See https://cert-manager.io/docs/configuration/acme/#creating-a-basic-acme-issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration.
    email: admin@netwerkdigitaalerfgoed.nl # TODO: change this!
    # Name of a secret used to store the ACME account private key.
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Let’s Encrypt HTTP-01 challenge provider.
    solvers:
      - http01:
          ingress:
            class: nginx
