apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataset-knowledge-graph
spec:
  schedule: "15 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/netwerk-digitaal-erfgoed/dataset-knowledge-graph
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /app/imports
                  name: imports
              env:
                - name: QLEVER_ENV
                  value: native
                - name: QLEVER_PORT
                  value: "7100" # Should not be necessary but without this we get “Error: env/QLEVER_PORT must be number”.
                - name: GRAPHDB_URL
                  value: "http://graphdb"
                - name: GRAPHDB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: graphdb
                      key: username
                - name: GRAPHDB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: graphdb
                      key: password
              resources:
                requests:
                  cpu: "2"
                limits:
                  cpu: "3"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ghcr
          volumes:
            - name: imports
              persistentVolumeClaim:
                claimName: dataset-knowledge-graph-imports
          securityContext:
            fsGroup: 100
        metadata:
          labels:
            app: dataset-knowledge-graph
