apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-knowledge-graph-imports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: do-block-storage
