apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-knowledge-graph-imports
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: do-block-storage
