apiVersion: apps/v1
kind: Deployment
metadata:
  name: gvn-search-find
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gvn-search-find
  template:
    metadata:
      labels:
        app: gvn-search-find
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/gvn-search-find
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr
