apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-crawler
  template:
    metadata:
      labels:
        app: registry-crawler
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/dataset-register
          env:
            - name: SPARQL_URL
              value: "http://dataset-register-qlever"
            - name: SPARQL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dataset-register-qlever
                  key: access-token
            - name: CRAWLER_SCHEDULE
              value: '0 * * * *'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT # This is being used by the sidecar. Should it be used by the app itself?
              value: "http://opentelemetry-collector:4318"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr
