apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry-api
  template:
    metadata:
      labels:
        app: registry-api
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/registry-api
          env:
            - name: GRAPHDB_URL
              value: "http://graphdb"
            - name: GRAPHDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: graphdb
                  key: username
            - name: GRAPHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graphdb
                  key: password
            - name: DOCS_URL
              value: "/register-api"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr
