apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry-api
  template:
    metadata:
      labels:
        app: registry-api
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/registry-api
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr
