# See https://www.digitalocean.com/docs/kubernetes/how-to/add-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-demo-datasets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
