persistence:
  enabled: true

ingress:
  enabled: true
  hosts:
    - statistieken.nde-dev.ms4.surfsara.nl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: nginx-nde
  tls:
    - hosts:
        - statistieken.nde-dev.ms4.surfsara.nl
      secretName: statistieken-tls

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: victoriametrics
        type: prometheus
        orgId: 1
        url: http://vmsingle-victoriametrics-single-persisted.default.svc:8429
        access: proxy
        isDefault: true
        updateIntervalSeconds: 10
        editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    victoriametrics:
      gnetId: 11176
      revision: 18
      datasource: victoriametrics
    vmagent:
      gnetId: 12683
      revision: 7
      datasource: victoriametrics
    kubernetes:
      gnetId: 14205
      revision: 1
      datasource: victoriametrics
