apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-api
  template:
    metadata:
      labels:
        app: registry-api
# Enabling auto-instrumentation causes metrics to fail with the following error, so disable for now:
# {"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error)\n    at doExport (/otel-auto-instrumentation/node_module)
#      annotations:
#        instrumentation.opentelemetry.io/inject-nodejs: "true" # Works, as it triggers all kinds of log messages
    spec:
      containers:
        - name: app
          image: ghcr.io/netwerk-digitaal-erfgoed/dataset-register/apps-api
          env:
            - name: SPARQL_URL
              value: "http://dataset-register-qlever"
            - name: SPARQL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dataset-register-qlever
                  key: access-token
            - name: TRUST_PROXY
              value: 'true'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT # This is being used by the sidecar. Should it be used by the app itself?
              value: "http://opentelemetry-collector:4318"
            - name: OTEL_LOG_LEVEL
              value: "all"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr
