apiVersion: batch/v1
kind: CronJob
metadata:
  name: geonames-sparql-harvester
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - geonames-sparql
                  topologyKey: kubernetes.io/hostname
          serviceAccountName: statefulset-manager
          initContainers:
            - name: harvester
              image: ghcr.io/netwerk-digitaal-erfgoed/geonames-rdf
              imagePullPolicy: Always
              volumeMounts:
                - name: data
                  mountPath: /app/data
          # Restart Fuseki to reload harvested data.
          containers:
            - name: restart
              image: bitnamisecure/kubectl:sha256-19163f0c3febd59f1c401170e198189ddfdea470b611bb5f25a2b043b99518ae
              args: ["rollout", "restart", "statefulset/geonames-sparql"]
          restartPolicy: OnFailure
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-geonames-sparql-0
          imagePullSecrets:
            - name: ghcr
