apiVersion: batch/v1
kind: CronJob
metadata:
  name: geonames-sparql-harvester
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: harvester
              image: ghcr.io/netwerk-digitaal-erfgoed/geonames-harvester
              command: ["/bin/sh", "-c", "./geonames-download.sh && ./map.sh"]
              volumeMounts:
                - name: data
                  mountPath: /app/data
          containers:
            - name: restart
              image: bitnami/kubectl:1.25.3
              command: ["kubectl rollout restart statefulset/geonames-sparql"]
          restartPolicy: OnFailure
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-geonames-sparql-0
          imagePullSecrets:
            - name: ghcr
