apiVersion: v1
kind: ConfigMap
metadata:
  name: geonames-fuseki-config
data:
  config.ttl: |
    @prefix :       <#> .
    @prefix fuseki: <http://jena.apache.org/fuseki#> .
    @prefix gn:     <https://www.geonames.org/ontology#> .
    @prefix tdb2:   <http://jena.apache.org/2016/tdb#> .
    @prefix text:   <http://jena.apache.org/text#> .
    
    [] a fuseki:Server ;
       fuseki:services (:geonames) .
    
    :geonames a fuseki:Service ;
              fuseki:name "geonames2" ;
              fuseki:label "GeoNames" ;
              fuseki:serviceQuery "sparql" ;
              fuseki:serviceReadGraphStore "get" ;
              fuseki:dataset :textDataset ;
    .
    
    :textDataset a text:TextDataset ;
      text:dataset :dataset ;
      text:index :index ;
    .
    
    :dataset a tdb2:DatasetTDB2 ;
      tdb2:location "/data/tdb" ;
    .
    
    :index a text:TextIndexLucene ;
      text:directory <file:/data/index> ;
      text:entityMap :entityMap ;
      text:analyzer [
        a text:ConfigurableAnalyzer ;
        text:tokenizer text:StandardTokenizer ;
        text:filters ( text:ASCIIFoldingFilter text:LowerCaseFilter ) ;
      ] ;
    .
    
    :entityMap a text:EntityMap ;
      text:defaultField "name" ;
      text:entityField "uri" ;
      text:map (
        [
          text:field "name" ;
          text:predicate gn:name ;
          text:boost 3.0 ;
        ]
        [
          text:field "alternateName" ;
          text:predicate gn:alternateName ;
        ]    
        [
          text:field "countryCode" ;
          text:predicate gn:countryCode ;
        ]    
      ) ;
    .
