# https://velero.io/docs/latest/api-types/schedule/#docs
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: cluster-backup
  namespace: velero
spec:
  schedule: 0 2 * * *
  template:
    includedNamespaces:
      - default
    ttl: 168h # 1 week
