apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-of-terms-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-of-terms-demo
  template:
    metadata:
      labels:
        app: network-of-terms-demo
    spec:
      containers:
        - name: network-of-terms-demo
          image: docker.pkg.github.com/netwerk-digitaal-erfgoed/network-of-terms-demo/network-of-terms-demo
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: network-of-terms-demo
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: network-of-terms-demo
