# See https://www.digitalocean.com/docs/kubernetes/how-to/add-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
