apiVersion: apps/v1
kind: StatefulSet # https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors/#dobs-pod-owner
metadata:
  name: graphdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphdb
  serviceName: graphdb
  template:
    metadata:
      labels:
        app: graphdb
    spec:
      containers:
        - name: database
          image: ontotext/graphdb:10.4.1
          resources:
            requests:
              memory: 1.5Gi
            limits:
              memory: 8Gi
          env:
            - name: GDB_JAVA_OPTS
              value: |
                -Dgraphdb.workbench.cors.enable=true
                -Dgraphdb.engine.parallel-import=false
            - name: GDB_HEAP_SIZE
              value: 6g
          volumeMounts:
            - mountPath: "/opt/graphdb/home"
              name: data
          ports:
            - containerPort: 7200
      imagePullSecrets:
        - name: ghcr
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi # Changed to 20Gi.
        storageClassName: do-block-storage
