apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataset-knowledge-graph
spec:
  schedule: "15 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/netwerk-digitaal-erfgoed/dataset-knowledge-graph
              imagePullPolicy: Always
              env:
                - name: QLEVER_ENV
                  value: native
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ghcr
        metadata:
          labels:
            app: dataset-knowledge-graph
