apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dataset-knowledge-graph-graphdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataset-knowledge-graph-graphdb
  serviceName: dataset-knowledge-graph-graphdb
  template:
    metadata:
      labels:
        app: dataset-knowledge-graph-graphdb
    spec:
      containers:
        - name: database
          image: ontotext/graphdb:10.7.3
          resources:
            requests:
              memory: 1.5Gi
            limits:
              memory: 13Gi
          env:
            - name: GDB_JAVA_OPTS
              value: |
                -Dgraphdb.workbench.cors.enable=true
                -Dgraphdb.engine.parallel-import=false
                -Dhealth.max.query.time.seconds=60
            - name: GDB_HEAP_SIZE
              value: 9g
          volumeMounts:
            - mountPath: "/opt/graphdb/home"
              name: data
          ports:
            - containerPort: 7200
          livenessProbe:
            httpGet:
              path: /repositories/dataset-knowledge-graph-imports/health?passive
              port: 7200
            initialDelaySeconds: 200
            periodSeconds: 5
            timeoutSeconds: 60
      imagePullSecrets:
        - name: ghcr
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: hdd
