apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dataset-knowledge-graph-graphdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataset-knowledge-graph-graphdb
  serviceName: dataset-knowledge-graph-graphdb
  template:
    metadata:
      labels:
        app: dataset-knowledge-graph-graphdb
    spec:
      containers:
        - name: database
          image: ontotext/graphdb:10.5.0
          resources:
            requests:
              memory: 1.5Gi
            limits:
              memory: 6Gi
          env:
            - name: GDB_JAVA_OPTS
              value: |
                -Dgraphdb.workbench.cors.enable=true
                -Dgraphdb.engine.parallel-import=false
            - name: GDB_HEAP_SIZE
              value: 3g
          volumeMounts:
            - mountPath: "/opt/graphdb/home"
              name: data
          ports:
            - containerPort: 7200
      imagePullSecrets:
        - name: ghcr
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: do-block-storage
